language: python
python:
  - "3.6"      # current default Python on Travis CI
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - "python setup.py install"
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pytest